apiVersion: v1
kind: Secret
metadata:
  namespace: devops-demo
  name: php-db-config
type: Opaque
data:
  db.config: REJfSE9TVD1wb3N0Z3JlcwpEQl9QT1JUPTU0MzIKREJfTkFNRT1hcHBfcGhwCkRCX1VTRVI9cGhwX3VzZXIKREJfUEFTU1dPUkQ9ZXhhbXBsZV9wYXNzd29yZApEQl9TU0xfTU9ERT1kaXNhYmxl

---

apiVersion: v1
kind: Secret
metadata:
  namespace: devops-demo
  name: golang-db-config
type: Opaque
data:
  db.config: REJfSE9TVD1wb3N0Z3JlcwpEQl9QT1JUPTU0MzIKREJfTkFNRT1hcHBfZ29sYW5nCkRCX1VTRVI9Z29sYW5nX3VzZXIKREJfUEFTU1dPUkQ9ZXhhbXBsZV9wYXNzd29yZApEQl9TU0xfTU9ERT1kaXNhYmxl
