---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: golang-ingress
  namespace: devops-demo
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`localhost`) && PathPrefix(`/go/`)
      kind: Rule
      services:
        - name: golang-service
          port: 8080

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: php-ingress
  namespace: devops-demo
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`localhost`) && PathPrefix(`/php/`)
      kind: Rule
      services:
        - name: php-service
          port: 8080