{{- range $appName, $app := .Values.apps }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $appName }}-aws-secrets
  namespace: devops-demo
spec:
  provider: aws
  parameters:
    region: {{ $.Values.global.region }}
    objects: |
      - objectName: {{ $app.database.managed.secretKey }}
        objectType: secretsmanager

{{- end }}