{{- range $appName, $app := .Values.apps }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $appName }}-service-account
  namespace: devops-demo
  annotations:
    eks.amazonaws.com/role-arn: {{ $app.security.secretsIamRoleArn }}

{{- end }}