apiVersion: v2
name: devops-sample-apps
description: A Helm chart for Go and PHP sample applications
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - golang
  - php
  - web
  - applications
home: https://github.com/docplanner/devops-sample-apps
sources:
  - https://github.com/docplanner/devops-sample-apps
